//
// Created by 20075 on 2024/6/4.
//

#ifndef EBLOCK_EBLOCKERRORS_H
#define EBLOCK_EBLOCKERRORS_H

/**内核模块和用户态交互的所有错误码*************/
#define EBLOCK_ERROR_TYPE_OK            0
//自定义错误码从50000开始
#define EBLOCK_ERROR_TYPE_OPEN_FAILD    50001
#define EBLOCK_ERROR_TYPE_IOCTL_EXE     50002
#define EBLOCK_ERROR_TYPE_READ_FAILED   50003
#define EBLOCK_ERROR_TYPE_WRITE_FAILED  50004
#define EBLOCK_ERROR_TYPE_READ_NODATA   50005

#endif //EBLOCK_EBLOCKERRORS_H
